### ISSUE TITLE
Show pagination in one row if there is enough space

### ISSUE THREAD

**Issue by Eyhenij** [Eyhenij/rt-tools#71]
<img width="878" alt="image" src="https://github.com/user-attachments/assets/5754ec02-a8a9-4c55-adb2-c673e7c478d0">

**Comment by Eyhenij** [comment]
@olgaSokolovskaya1991, возьми в работу плз

**Comment by olgaSokolovskaya1991** [comment]
-Перейти на страницы reports, roles или hotels (в данном случае- roles);
-Выбрать количество сущностей на странице 40 или 50;
-Ввести в строку поиска количество символов такое, чтобы количество сущностей по результату поиска помещалось в одну страницу (в данном случае- "12");
-В строке поиска удалить символ(-ы) до количества сущностей по результату поиска больше 10 (в данном случае- "1");

Результат: Не отображается количество символов на странице

https://github.com/user-attachments/assets/8553261a-59d0-457e-bb96-5f4cd9ca02eb

![Image](https://github.com/user-attachments/assets/82ea618c-7331-4ab0-acea-c82c89b3d665)

**Comment by Eyhenij** [comment]
@olgaSokolovskaya1991 , обрати пожалуйста внимание что этот тикет их rt-tools, он не имеет отношения к авалону, тебе нужно протестировать компонент пагинации именно в rt-tools, стяни себе актуальную ветку main и запусти локально сторибук.

**Comment by Eyhenij** [comment]
@olgaSokolovskaya1991 , по описанному тобой выше поведению заведи плз багу

**Comment by olgaSokolovskaya1991** [comment]
approved
